# Identificación del proyecto
sonar.projectKey=celiasuaco_esencia
sonar.organization=celiasuaco
sonar.projectName=Esencia

# Rutas de código fuente
# Analizamos las carpetas de lógica, excluyendo lo innecesario
sonar.sources=backend,frontend
sonar.exclusions=**/volumes/**, **/venv/**, **/node_modules/**, **/migrations/**, backend/manage.py

# Configuración de lenguajes
sonar.python.version=3.11
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Codificación
sonar.sourceEncoding=UTF-8