# Generated by Django 5.0.3 on 2026-04-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ANILLO', 'Anillo'), ('COLLAR', 'Collar'), ('PENDIENTE', 'Pendiente'), ('PULSERA', 'Pulsera')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, default='products/default_product.png', null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.CharField(default='Oro 18k', max_length=50)),
            ],
        ),
    ]
